-- 테스트용 상담기록 데이터 추가
INSERT INTO consultation_records (
    consultation_id, 
    client_id, 
    consultant_id, 
    session_date, 
    session_number, 
    client_condition, 
    main_issues, 
    intervention_methods, 
    client_response, 
    next_session_plan, 
    homework_assigned, 
    risk_assessment, 
    progress_evaluation, 
    progress_score, 
    goal_achievement, 
    consultant_observations, 
    consultant_assessment, 
    session_duration_minutes, 
    is_session_completed, 
    completion_time, 
    created_at, 
    updated_at, 
    is_deleted
) VALUES (
    1, 
    1, 
    1, 
    '2024-09-14', 
    1, 
    '안정적인 상태', 
    '스트레스 관리', 
    '인지행동치료', 
    '긍정적인 반응', 
    '다음 주 동일한 시간', 
    '일기 작성', 
    'LOW', 
    '양호한 진행', 
    75, 
    'MEDIUM', 
    '내담자가 적극적으로 참여하고 있음', 
    '전반적으로 만족스러운 진행', 
    60, 
    true, 
    '2024-09-14 10:00:00', 
    NOW(), 
    NOW(), 
    false
);
