/**
 * 텍스트 상수 정의
 * 모든 사용자에게 보이는 텍스트를 한 곳에서 관리
 * 하드코딩 금지 - 모든 텍스트는 여기서 관리
 */

// 공통 메시지
export const COMMON_STRINGS = {
  LOADING: '로딩 중...',
  LOADING_DATA: '데이터를 불러오는 중...',
  ERROR: '오류',
  SUCCESS: '성공',
  SAVE: '저장',
  CANCEL: '취소',
  CONFIRM: '확인',
  DELETE: '삭제',
  EDIT: '수정',
  VIEW: '보기',
  CLOSE: '닫기',
  SEARCH: '검색',
  FILTER: '필터',
  ALL: '전체',
  NO_DATA: '데이터가 없습니다.',
  WARNING: '경고',
  INFO: '알림',
  CONFIRM_DEFAULT_MESSAGE: '정말로 진행하시겠습니까?',
  BACK: '돌아가기',
  BACK_TO_LIST: '목록으로 돌아가기',
  SEND: '전송',
  RETRY: '다시 시도',
  CREATE: '생성',
  DENY: '거부',
  ALLOW: '허용',
};

// 시간 관련
export const TIME_STRINGS = {
  AM: '오전',
  PM: '오후',
  TODAY: '오늘',
  YESTERDAY: '어제',
  TOMORROW: '내일',
  DAYS_AGO: '일 전',
};

// 인사말
export const GREETING_STRINGS = {
  MORNING: '좋은 아침이에요',
  AFTERNOON: '좋은 오후예요',
  EVENING: '좋은 저녁이에요',
  CLIENT_SUBTITLE: '오늘도 힐링하는 하루 되세요',
  CONSULTANT_SUBTITLE: '오늘도 따뜻한 상담하세요',
  CLIENT_DEFAULT_NAME: '내담자',
  CONSULTANT_DEFAULT_NAME: '상담사',
};

// 내담자 관련 텍스트
export const CLIENT_STRINGS = {
  NAME_EMAIL_PHONE: '이름, 이메일, 전화번호로 검색',
  SEARCH_PLACEHOLDER: '이름, 이메일, 전화번호로 검색',
  JOIN_DATE: '가입일',
  DASHBOARD_TITLE: '내담자 대시보드',
  TODAY_CONSULTATION: '오늘의 상담',
  COMPLETED_CONSULTATION: '완료한 상담',
  WEEKLY_CONSULTATION: '이번 주 상담',
  REMAINING_SESSIONS: '잔여 회기',
  PHONE: '전화번호',
  LAST_LOGIN: '최근 로그인',
  ACTIVE_CLIENTS: '활성 내담자',
  NEW_CLIENTS: '신규 내담자',
  NO_CLIENTS_FOUND: '검색 결과가 없습니다.',
  SCHEDULE_TITLE: '상담 일정',
  SCHEDULE_EMPTY: '해당 날짜에 예정된 상담이 없습니다.',
  MESSAGES_TITLE: '메시지',
  ALL_MESSAGES: '전체 메시지',
  UNREAD_MESSAGES: '읽지 않음',
  IMPORTANT_MESSAGES: '중요 메시지',
  URGENT_MESSAGES: '긴급 메시지',
  NO_MESSAGES: '받은 메시지가 없습니다.',
  PAYMENT_TITLE: '결제 내역',
  ALL_PAYMENTS: '전체 결제',
  TOTAL_PAYMENT_AMOUNT: '총 결제 금액',
  NO_PAYMENTS: '결제 내역이 없습니다.',
  SETTINGS_TITLE: '내 정보',
  PROFILE_IMAGE: '프로필 사진',
  BASIC_INFO: '기본 정보',
  NAME: '이름',
  NICKNAME: '닉네임',
  EMAIL: '이메일',
  EMAIL_NOT_EDITABLE: '이메일은 변경할 수 없습니다.',
  QUICK_ACTIONS: '빠른 메뉴',
  QUICK_ACTION_ITEMS: {
    SCHEDULE: '상담 일정',
    MESSAGES: '메시지',
    PAYMENT: '결제 내역',
    SETTINGS: '내 정보',
  },
};

// 상담사 관련 텍스트
export const CONSULTANT_STRINGS = {
  DASHBOARD_TITLE: '상담사 대시보드',
  SETTINGS_TITLE: '내 정보',
  TODAY_CONSULTATION: '오늘 상담',
  TOTAL_CLIENTS: '내담자 수',
  COMPLETED_CONSULTATION: '완료 상담',
  AVERAGE_RATING: '평균 평가',
  CONSULTATION_RECORDS: '상담일지',
  PENDING_RECORDS: '미완료 일지',
  SCHEDULE_TITLE: '스케줄 관리',
  SCHEDULE_EMPTY: '해당 날짜에 예정된 상담이 없습니다.',
  NO_SCHEDULE: '예정된 상담이 없습니다.',
  CREATE_SCHEDULE: '새 상담 일정 추가',
  COMPLETED: '완료된 상담',
  SCHEDULED: '예정된 상담',
  STATISTICS_TITLE: '통계',
  TOTAL_RATINGS: '총 평가 수',
  COMPLETION_RATE: '완료율',
  TOTAL_SESSIONS: '총 상담 수',
  CONSULTATION_STATS: '상담 통계',
  TAB_STATISTICS: '통계',
  BASIC_INFO: '기본 정보',
  SESSION_NUMBER: '세션 번호',
  CONSULTATION_TIME: '상담 시간',
  CONSULTATION_TYPE: '상담 유형',
  SESSION_DATE: '상담 날짜',
  CONSULTATION_CONTENT: '상담 내용',
  INDIVIDUAL_CONSULTATION: '개별 상담',
  NO_TIME: '시간 정보 없음',
  NO_INFO: '정보 없음',
  NO_CONSULTATION_CONTENT: '작성된 상담 내용이 없습니다.',
  QUICK_ACTIONS: '빠른 메뉴',
  QUICK_ACTION_ITEMS: {
    SCHEDULE: '일정 관리',
    CLIENTS: '내담자 관리',
    MESSAGES: '메시지',
    RECORDS: '상담일지',
  },
  CLIENT_LIST: '내담자 목록',
  NO_CLIENTS: '등록된 내담자가 없습니다.',
  NO_CLIENTS_FOUND: '검색 결과가 없습니다.',
  NO_CLIENTS_HINT: '새로운 내담자가 매칭되면 여기에 표시됩니다.',
  SEARCH_PLACEHOLDER: '이름, 이메일, 전문 분야로 검색',
  TOTAL_CONSULTANTS: '총 상담사',
  ACTIVE_CONSULTANTS: '활성 상담사',
  CONSULTANT_LIST: '상담사 목록',
  NO_CONSULTANTS: '등록된 상담사가 없습니다.',
  NO_CONSULTANTS_FOUND: '검색 결과가 없습니다.',
  SPECIALTY: '전문 분야',
};

// 스케줄 관련 텍스트
export const SCHEDULE_STRINGS = {
  CALENDAR: '일정 캘린더',
  SCHEDULE_FOR_DATE: (date) => `${date} 일정`, // 함수는 사용 시 호출
  DATE: '날짜',
  TIME: '시간',
  START_TIME: '시작 시간',
  END_TIME: '종료 시간',
  TITLE: '제목',
  TITLE_PLACEHOLDER: '상담 제목을 입력하세요',
  NOTES: '메모',
  NOTES_PLACEHOLDER: '상담 내용을 간단히 적어주세요',
  STATUS: {
    COMPLETED: '완료',
    CANCELLED: '취소',
    SCHEDULED: '예정',
    BOOKED: '예약됨',
  },
  CONSULTANT: '상담사',
  CLIENT: '내담자',
  FILL_REQUIRED_FIELDS: '필수 항목을 모두 입력해주세요.',
  SCHEDULE_CREATED: '스케줄이 생성되었습니다.',
  CLIENT_SELECTION: '내담자 선택',
};

// 메시지 관련 텍스트
export const MESSAGE_STRINGS = {
  TITLE: '메시지',
  DETAIL_TITLE: '메시지 상세',
  SENDER: '발신자',
  RECEIVER: '수신자',
  FROM: '보낸 사람',
  URGENT: '긴급',
  IMPORTANT: '중요',
  UNREAD: '읽지 않음',
  READ: '읽음',
  REPLY: '답장',
  REPLY_PREFIX: 'Re:',
  REPLY_PLACEHOLDER: '답장 내용을 입력하세요...',
  SEND: '전송',
};

// 결제 관련 텍스트
export const PAYMENT_STRINGS = {
  TITLE: '결제 내역',
  TOTAL_AMOUNT: '총 결제 금액',
  PAYMENT_METHOD: '결제 수단',
  PAYMENT_DATE: '결제일',
  STATUS: {
    COMPLETED: '완료',
    PENDING: '대기',
    CANCELLED: '취소',
  },
};

// 프로필 관련 텍스트
export const PROFILE_STRINGS = {
  NAME: '이름',
  NICKNAME: '닉네임',
  EMAIL: '이메일',
  PHONE: '전화번호',
  PROFILE_IMAGE: '프로필 사진',
  CHANGE_IMAGE: '프로필 이미지 변경',
  EMAIL_NOT_EDITABLE: '이메일은 변경할 수 없습니다.',
  ENTER_NAME: '이름을 입력하세요',
  ENTER_NICKNAME: '닉네임을 입력하세요',
  ENTER_PHONE: '전화번호를 입력하세요',
  SAVING: '저장 중...',
  SAVE_BUTTON: '저장하기',
};

// 로그인 관련 텍스트
export const AUTH_STRINGS = {
  LOGIN_TITLE: '마인드가든 로그인',
  LOGIN_SUBTITLE: '본사 또는 지점별로 로그인하세요',
  TABS: {
    EMAIL: '이메일 로그인',
    SNS: 'SNS 로그인',
  },
  HEADQUARTERS_LOGIN: '본사 로그인',
  BRANCH_LOGIN: '지점 로그인',
  SELECT_BRANCH: '지점 선택',
  SELECT_BRANCH_PLACEHOLDER: '지점을 선택하세요',
  EMAIL_LABEL: '이메일',
  PASSWORD_LABEL: '비밀번호',
  EMAIL_PLACEHOLDER: '이메일을 입력하세요',
  PASSWORD_PLACEHOLDER: '비밀번호를 입력하세요',
  LOGIN_BUTTON: '로그인',
  LOGIN_SUCCESS: '로그인에 성공했습니다.',
  LOGIN_FAILED: '로그인에 실패했습니다.',
  LOGIN_ERROR: '로그인 처리 중 오류가 발생했습니다.',
  DUPLICATE_LOGIN: '중복 로그인',
  INPUT_ERROR: '입력 오류',
  EMAIL_PASSWORD_REQUIRED: '이메일과 비밀번호를 입력해주세요.',
  BRANCH_CODE_REQUIRED: '지점 코드를 선택해주세요.',
  BRANCH_LIST_LOAD_FAILED: '지점 목록을 불러오는데 실패했습니다.',
  HEADQUARTERS_INFO_TITLE: '본사 로그인',
  HEADQUARTERS_INFO_TEXT: '본사 관리자만 로그인 가능합니다. 전체 지점 관리 및 통계 조회가 가능합니다.',
  BRANCH_INFO_TITLE: '지점 로그인',
  BRANCH_INFO_TEXT: '해당 지점에 소속된 사용자만 로그인 가능합니다. 지점별 상담사/내담자 관리가 가능합니다.',
  SMS_LOGIN_MODE: 'SMS 로그인',
  PHONE_NUMBER_LABEL: '휴대폰 번호',
  PHONE_NUMBER_PLACEHOLDER: '010-0000-0000',
  SEND_VERIFICATION_CODE: '인증번호 전송',
  VERIFICATION_CODE_LABEL: '인증 코드',
  VERIFICATION_CODE_PLACEHOLDER: '6자리 인증 코드',
  VERIFY_CODE: '인증',
  SMS_LOGIN_BUTTON: 'SMS 로그인',
  SMS_SENT_SUCCESS: '인증번호가 전송되었습니다.',
  SMS_VERIFY_SUCCESS: '인증에 성공했습니다.',
  SMS_VERIFY_FAILED: '인증에 실패했습니다. 코드를 확인해주세요.',
  SMS_SEND_FAILED: '인증번호 전송에 실패했습니다.',
  PHONE_INVALID: '유효한 휴대폰 번호를 입력해주세요.',
  CODE_INVALID: '유효한 인증 코드를 입력해주세요.',
  FORGOT_PASSWORD: '비밀번호를 잊으셨나요?',
  NO_ACCOUNT_PROMPT: '계정이 없으신가요?',
  REGISTER_LINK: '회원가입',
  EMAIL_LOGIN_MODE: '이메일 로그인', // 이메일 로그인 모드 추가
  LOGOUT: '로그아웃',
  LOGOUT_CONFIRM_TITLE: '로그아웃',
  LOGOUT_CONFIRM_MESSAGE: '정말 로그아웃하시겠습니까?',
  LOGOUT_SUCCESS: '로그아웃되었습니다.',
  LOGOUT_ERROR: '로그아웃에 실패했습니다.',
  ACCOUNT: '계정',
  SOCIAL: {
    OR: '또는',
    KAKAO_LOGIN: '카카오로 로그인',
    NAVER_LOGIN: '네이버로 로그인',
    SIGNUP_REQUIRED: '소셜 로그인 계정으로 회원가입이 필요합니다.',
  },
};

// 사용자 관리 관련 텍스트
export const USER_STRINGS = {
  SEARCH_PLACEHOLDER: '이름, 이메일로 검색',
  ACTIVATED: '활성화되었습니다.',
  DEACTIVATED: '비활성화되었습니다.',
  DELETE_CONFIRM: '님을 삭제하시겠습니까?',
  ROLE_CLIENT: '내담자',
  ROLE_CONSULTANT: '상담사',
  ROLE_ADMIN: '관리자',
  ROLE_HQ_ADMIN: '본사 관리자',
  STATUS_ACTIVE: '활성',
  STATUS_INACTIVE: '비활성',
  STATUS_PENDING: '대기',
  STATUS: '상태',
  ROLE: '역할',
  USER_STATISTICS: '사용자 통계',
  USER_LIST: '사용자 목록',
  NO_NAME: '이름 없음',
  NO_EMAIL: '이메일 없음',
  CREATED_AT: '가입일',
  DEACTIVATE: '비활성화',
  ACTIVATE: '활성화',
  NO_USERS_FOUND: '검색 결과가 없습니다.',
  NO_USERS: '등록된 사용자가 없습니다.',
  UPDATE_FAILED: '업데이트에 실패했습니다.',
};

// 관리자 관련 텍스트
export const ADMIN_STRINGS = {
  DASHBOARD_TITLE: '관리자 대시보드',
  USER_MANAGEMENT: '사용자 관리',
  CONSULTANT_MANAGEMENT: '상담사 관리',
  CLIENT_MANAGEMENT: '내담자 관리',
  MAPPING_MANAGEMENT: '매칭 관리',
  SESSION_MANAGEMENT: '세션 관리',
  STATISTICS_DASHBOARD: '통계',
  ERP_DASHBOARD: 'ERP',
  FINANCIAL_MANAGEMENT: '재무 관리',
  SALARY_MANAGEMENT: '급여 관리',
  TOTAL_USERS: '전체 사용자',
  TOTAL_CONSULTANTS: '전체 상담사',
  TOTAL_CLIENTS: '전체 내담자',
  TOTAL_MAPPINGS: '전체 매칭',
  SYSTEM_STATUS: '시스템 상태',
  SYSTEM_HEALTH: '시스템 건강도',
  STATUS_GOOD: '정상',
  STATUS_WARNING: '경고',
  STATUS_ERROR: '오류',
  TODAY_ACTIVITIES: '오늘의 활동',
  TODAY_SCHEDULES: '오늘의 일정',
  PENDING_MESSAGES: '대기 중인 메시지',
  PENDING_RECORDS: '대기 중인 기록',
  QUICK_ACTIONS: '빠른 액션',
};

// 매칭 관련 텍스트
export const MAPPING_STRINGS = {
  ACTIVE_MAPPINGS: '활성 매칭',
  UNMAPPED_CLIENTS: '미매칭 내담자',
  CONSULTANT_MAPPINGS: '상담사별 매칭 현황',
  MAPPED_CLIENTS: '매칭된 내담자',
  MAPPED_DATE: '매칭일',
  NO_MAPPED_CLIENTS: '매칭된 내담자가 없습니다.',
  ADD_MAPPING: '내담자 매칭',
  CREATE_MAPPING: '매칭하기',
  MAPPING_CREATED: '매칭이 생성되었습니다.',
  MAPPING_DELETED: '매칭이 해제되었습니다.',
  // 결제 정보 입력 모달
  PAYMENT_INFO_TITLE: '회기 및 결제 정보 입력',
  PAYMENT_INFO_SECTION: '매칭 정보',
  SESSIONS_COUNT: '회기 수',
  PACKAGE_NAME: '패키지명',
  PACKAGE_NAME_PLACEHOLDER: '예: 기본 10회기 패키지',
  PACKAGE_PRICE: '패키지 가격 (원)',
  PACKAGE_PRICE_PLACEHOLDER: '500000',
  PAYMENT_METHOD: '결제 방법',
  PAYMENT_REFERENCE: '결제 참조번호',
  PAYMENT_REFERENCE_PLACEHOLDER: '자동 생성',
  RESPONSIBILITY: '책임자',
  RESPONSIBILITY_PLACEHOLDER: '예: 정신건강 상담',
  SPECIAL_CONSIDERATIONS: '특별 고려사항',
  SPECIAL_CONSIDERATIONS_PLACEHOLDER: '특별 고려사항을 입력하세요',
  NOTES: '메모',
  NOTES_PLACEHOLDER: '추가 메모를 입력하세요',
  CREATING_MAPPING: '매칭 생성 중...',
  CREATE_MAPPING_BUTTON: '매칭 생성',
  DELETE_CONFIRM: '정말로 이 매칭을 해제하시겠습니까?',
  // 결제 확인
  CONFIRM_PAYMENT: '결제 확인',
  CONFIRM_PAYMENT_TITLE: '결제 확인',
  PAYMENT_AMOUNT: '결제 금액',
  PAYMENT_AMOUNT_PLACEHOLDER: '금액 입력',
  CONSULTATION_TYPE: '상담종류',
  CONSULTATION_TYPE_PLACEHOLDER: '상담종류 입력',
};

// 세션 관리 관련 텍스트
export const SESSION_STRINGS = {
  TOTAL_SESSIONS: '총 세션',
  PENDING: '대기',
  SESSION_LIST: '세션 목록',
  MARK_COMPLETED: '완료 처리',
  CANCEL_SESSION: '취소',
  APPROVE_SESSION: '승인',
  NO_SESSIONS: '등록된 세션이 없습니다.',
  NO_SESSIONS_FILTER: '해당 상태의 세션이 없습니다.',
  CREATE_NEW_SCHEDULE: '스케줄 생성',
  SELECT_MAPPING: '매칭 선택',
  SELECT_MAPPING_DESC: '스케줄을 생성할 상담사-내담자 매칭을 선택하세요',
  SELECT_DATE_TIME: '날짜/시간 선택',
  SELECT_DATE_TIME_DESC: '상담 일정을 선택하세요',
  NO_ACTIVE_MAPPINGS: '활성 매칭이 없습니다.',
  NO_ACTIVE_MAPPINGS_DESC: '먼저 매칭을 생성해주세요.',
  MAPPING_INFO: '매칭 정보',
  CONSULTANT_NAME: '상담사',
  CLIENT_NAME: '내담자',
  REMAINING_SESSIONS: '남은 회기',
  SESSION_DATE: '날짜',
  START_TIME: '시작 시간',
  END_TIME: '종료 시간',
  DATE_REQUIRED: '날짜를 선택해주세요',
  START_TIME_REQUIRED: '시작 시간을 입력해주세요',
  END_TIME_REQUIRED: '종료 시간을 입력해주세요',
  SCHEDULE_CREATED: '스케줄이 생성되었습니다.',
  SCHEDULE_CREATE_FAILED: '스케줄 생성에 실패했습니다.',
  INVALID_TIME_RANGE: '종료 시간은 시작 시간보다 늦어야 합니다.',
  DATE_FORMAT_PLACEHOLDER: 'YYYY-MM-DD',
  TIME_FORMAT_PLACEHOLDER: 'HH:MM',
  QUICK_TIME_SELECT: '빠른 선택',
  QUICK_TIME_MORNING_9_10: '오전 9-10시',
  QUICK_TIME_MORNING_10_11: '오전 10-11시',
  QUICK_TIME_MORNING_11_12: '오전 11-12시',
  QUICK_TIME_NOON_12_13: '오후 12-1시',
  QUICK_TIME_AFTERNOON_1_2: '오후 1-2시',
  QUICK_TIME_AFTERNOON_2_3: '오후 2-3시',
  QUICK_TIME_AFTERNOON_3_4: '오후 3-4시',
  QUICK_TIME_AFTERNOON_4_5: '오후 4-5시',
  QUICK_TIME_AFTERNOON_5_6: '오후 5-6시',
  QUICK_TIME_AFTERNOON_6_7: '오후 6-7시',
  QUICK_TIME_AFTERNOON_7_8: '오후 7-8시',
  TIME_ADJUST_30MIN: '30분',
  DURATION_SELECT: '상담 시간',
  DURATION_30_MIN: '30분',
  DURATION_50_MIN: '50분',
  DURATION_80_MIN: '80분',
  DURATION_100_MIN: '100분',
  START_TIME_SLOT_SELECT: '시작 시간 선택',
  START_TIME_SLOT_DESC: '30분 단위로 시간을 선택하세요',
};

// ERP 관련 텍스트
export const ERP_STRINGS = {
  BRANCH_STATUS: '지점 현황',
  TOTAL_BRANCHES: '총 지점 수',
  ACTIVE_BRANCHES: '활성 지점',
  TOTAL_EMPLOYEES: '총 직원 수',
  FINANCIAL_SUMMARY: '재무 요약',
  MONTHLY_REVENUE: '월 매출',
  MONTHLY_EXPENSES: '월 지출',
  PROFIT_MARGIN: '수익률',
  SYSTEM_ALERTS: '시스템 알림',
  RECENT_ACTIVITIES: '최근 활동',
  NO_RECENT_ACTIVITIES: '최근 활동이 없습니다.',
  PENDING_TASKS: '대기 작업',
  PENDING_TASKS_COUNT: '대기 중인 작업',
  MANAGE_TASKS: '작업 관리',
};

// 에러 메시지
export const ERROR_STRINGS = {
  LOAD_FAILED: '데이터를 불러오는데 실패했습니다.',
  SAVE_FAILED: '저장에 실패했습니다.',
  NETWORK_ERROR: '네트워크 오류가 발생했습니다.',
  LOGIN_REQUIRED: '로그인이 필요합니다.',
  PERMISSION_DENIED: '권한이 없습니다.',
  ERROR: '오류',
  CREATE_FAILED: '생성에 실패했습니다.',
  DELETE_FAILED: '삭제에 실패했습니다.',
  NOT_FOUND: '찾을 수 없습니다.',
};

// 통계 관련 텍스트
export const STATISTICS_STRINGS = {
  THIS_WEEK: '이번 주',
  THIS_MONTH: '이번 달',
  THIS_QUARTER: '이번 분기',
  THIS_YEAR: '올해',
  PERIOD: '기간',
  TOTAL_REVENUE: '총 매출',
  DETAILED_STATS: '상세 통계',
  CHARTS: '차트 분석',
  CHART_PLACEHOLDER: '차트 기능은 추후 구현 예정입니다.',
  CHART_DESCRIPTION: '사용자 성장, 세션 트렌드, 매출 추이 등의 시각적 분석을 제공합니다.',
  GENERATE_REPORT: '보고서 생성',
  REFRESH_DATA: '데이터 새로고침',
};

// 성공 메시지
export const SUCCESS_STRINGS = {
  SUCCESS: '성공',
  SAVED: '저장되었습니다.',
  DELETED: '삭제되었습니다.',
  UPDATED: '수정되었습니다.',
  SENT: '전송되었습니다.',
};

// 이미지 관련 텍스트
export const IMAGE_STRINGS = {
  TAKE_PHOTO: '사진 촬영',
  CHOOSE_FROM_GALLERY: '갤러리에서 선택',
  SELECT_IMAGE: '이미지 선택',
  SELECT_IMAGE_MESSAGE: '이미지를 선택하세요',
  CAMERA_PERMISSION_TITLE: '카메라 권한',
  CAMERA_PERMISSION_MESSAGE: '프로필 사진을 촬영하기 위해 카메라 권한이 필요합니다.',
  CAMERA_PERMISSION_DENIED: '카메라 권한이 거부되었습니다.',
  GALLERY_PERMISSION_TITLE: '갤러리 권한',
  GALLERY_PERMISSION_MESSAGE: '프로필 사진을 선택하기 위해 갤러리 접근 권한이 필요합니다.',
  GALLERY_PERMISSION_DENIED: '갤러리 접근 권한이 거부되었습니다.',
  CAMERA_ERROR: '카메라 촬영 중 오류가 발생했습니다.',
  GALLERY_ERROR: '갤러리에서 이미지를 불러오는데 실패했습니다.',
  CROP_TITLE: '이미지 크롭',
  CROP_ERROR: '이미지 크롭 중 오류가 발생했습니다.',
  UPLOAD_SUCCESS: '이미지가 업로드되었습니다.',
  UPLOAD_ERROR: '이미지 업로드에 실패했습니다.',
  UPLOAD_PHOTO: '업로드',
  CHANGE_PHOTO: '사진 변경',
  DELETE_CONFIRM: '프로필 이미지를 삭제하시겠습니까?',
};

// 전체 문자열 객체
export const STRINGS = {
  COMMON: COMMON_STRINGS,
  TIME: TIME_STRINGS,
  GREETING: GREETING_STRINGS,
  CLIENT: CLIENT_STRINGS,
  CONSULTANT: CONSULTANT_STRINGS,
  USER: USER_STRINGS,
  ADMIN: ADMIN_STRINGS,
  MAPPING: MAPPING_STRINGS,
  SESSION: SESSION_STRINGS,
  STATISTICS: STATISTICS_STRINGS,
  ERP: ERP_STRINGS,
  SCHEDULE: SCHEDULE_STRINGS,
  MESSAGE: MESSAGE_STRINGS,
  PAYMENT: PAYMENT_STRINGS,
  PROFILE: PROFILE_STRINGS,
  AUTH: AUTH_STRINGS,
  ERROR: ERROR_STRINGS,
  SUCCESS: SUCCESS_STRINGS,
  IMAGE: IMAGE_STRINGS,
};

export default STRINGS;

