-- source: dev DB (production D-1 copy), 2026-10-05
-- AUTO_INCREMENT start values and DEFINER removed. Columns, lengths, and constraints are unchanged.
-- queried_at: 2026-10-05 14:44:43 KST
CREATE TABLE `tenants` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '테넌트 내부 ID',
  `tenant_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '테넌트 ID (표준 형식: tenant-{지역코드}-{업종코드}-{순번})',
  `subdomain` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '서브도메인',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '테넌트명',
  `business_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('PENDING','ACTIVE','SUSPENDED','CLOSED') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `subscription_plan_id` bigint DEFAULT NULL COMMENT '구독 요금제 ID',
  `subscription_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'INACTIVE' COMMENT '구독 상태: INACTIVE, ACTIVE, SUSPENDED, CANCELLED',
  `subscription_start_date` date DEFAULT NULL COMMENT '구독 시작일',
  `subscription_end_date` date DEFAULT NULL COMMENT '구독 종료일',
  `contact_email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '연락 이메일',
  `contact_phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '연락 전화번호',
  `contact_person` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '담당자명',
  `postal_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '우편번호',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '주소',
  `address_detail` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '상세 주소',
  `settings_json` json DEFAULT NULL COMMENT '테넌트별 설정 (JSON)',
  `branding_json` json DEFAULT NULL COMMENT '브랜딩 정보 (로고, 색상 등)',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT '삭제일시 (소프트 삭제)',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '삭제 여부',
  `version` bigint DEFAULT '0' COMMENT '낙관적 잠금 버전',
  `lang_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'ko' COMMENT '언어 코드',
  `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '생성자',
  `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '수정자',
  `business_registration_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '사업자등록번호',
  `representative_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '대표자명',
  `business_landline` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '유선전화',
  `business_address` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '사업장 주소',
  `mail_order_report_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '통신판매업 신고번호',
  `refund_policy_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '환불·취소·청약철회 안내',
  `product_price_guide_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '상품·가격 안내',
  PRIMARY KEY (`id`),
  UNIQUE KEY `tenant_id` (`tenant_id`),
  UNIQUE KEY `tenant_id_2` (`tenant_id`),
  UNIQUE KEY `tenant_id_3` (`tenant_id`),
  UNIQUE KEY `idx_subdomain` (`subdomain`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_business_type` (`business_type`),
  KEY `idx_status` (`status`),
  KEY `idx_subscription_plan` (`subscription_plan_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_is_deleted` (`is_deleted`),
  KEY `idx_tenant_status` (`tenant_id`,`status`),
  KEY `idx_subdomain_lookup` (`subdomain`),
  CONSTRAINT `chk_business_type` CHECK ((`business_type` in (_utf8mb4'CONSULTATION',_utf8mb4'ACADEMY',_utf8mb4'FOOD_SERVICE',_utf8mb4'RETAIL',_utf8mb4'SERVICE',_utf8mb4'COUNSELING'))),
  CONSTRAINT `chk_tenant_status` CHECK ((`status` in (_utf8mb4'PENDING',_utf8mb4'ACTIVE',_utf8mb4'SUSPENDED',_utf8mb4'CLOSED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='테넌트(사업장) 정보 테이블 - 멀티테넌시 최상위 엔티티'
;
