-- source: dev DB (production D-1 copy), 2026-10-05
-- AUTO_INCREMENT start values and DEFINER removed. Columns, lengths, and constraints are unchanged.
-- queried_at: 2026-10-05 14:45:45 KST
CREATE TABLE `branches_dropped_20260612` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '생성자',
  `deleted_at` datetime(6) DEFAULT NULL,
  `is_deleted` bit(1) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '수정자',
  `lang_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'ko' COMMENT '언어 코드',
  `version` bigint NOT NULL,
  `address` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_detail` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `branch_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `branch_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `branch_settings` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `branch_status` enum('PLANNING','PREPARING','ACTIVE','SUSPENDED','CLOSED') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `branch_type` enum('MAIN','FRANCHISE','DIRECT','PARTNER') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `closed_days` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `closing_date` date DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fax_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `logo_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `max_clients` int DEFAULT NULL,
  `max_consultants` int DEFAULT NULL,
  `opening_date` date DEFAULT NULL,
  `operating_end_time` time(6) DEFAULT NULL,
  `operating_start_time` time(6) DEFAULT NULL,
  `phone_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postal_code` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `website_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `manager_id` bigint DEFAULT NULL,
  `parent_branch_id` bigint DEFAULT NULL,
  `tenant_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_aqmyw20ht3aku27r3oorfaw43` (`branch_code`),
  KEY `FKaxphe54ft6x2k2ndo8t5vsvjo` (`manager_id`),
  KEY `FKtp47j5rwpnpo1c3771sy5v991` (`parent_branch_id`),
  KEY `idx_branches_tenant_id` (`tenant_id`),
  KEY `idx_branches_tenant_status` (`tenant_id`,`branch_status`),
  CONSTRAINT `fk_branches_tenants` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FKaxphe54ft6x2k2ndo8t5vsvjo` FOREIGN KEY (`manager_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FKtp47j5rwpnpo1c3771sy5v991` FOREIGN KEY (`parent_branch_id`) REFERENCES `branches_dropped_20260612` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;
