-- source: dev DB (production D-1 copy), 2026-10-05
-- AUTO_INCREMENT start values and DEFINER removed. Columns, lengths, and constraints are unchanged.
-- queried_at: 2026-10-05 14:44:43 KST
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '생성자',
  `deleted_at` datetime(6) DEFAULT NULL,
  `is_deleted` bit(1) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '수정자',
  `lang_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'ko' COMMENT '언어 코드',
  `version` bigint NOT NULL,
  `address` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address_detail` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `age_group` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `email` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'PII (AES-256/CBC encrypted). EmailAttributeConverter SSOT. length>=512 per PII_PROTECTION_STANDARD §6.',
  `email_verification_expires_at` datetime(6) DEFAULT NULL,
  `email_verification_token` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `experience_points` bigint DEFAULT NULL,
  `gender` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `grade` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` bit(1) NOT NULL,
  `is_email_verified` bit(1) NOT NULL,
  `last_grade_update` datetime(6) DEFAULT NULL,
  `last_login_at` datetime(6) DEFAULT NULL,
  `tokens_invalidated_at` datetime DEFAULT NULL COMMENT '계정 단위 JWT 폐기 기준 시각(이전 발급 토큰 거부)',
  `memo` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `name` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'PII (AES-256/CBC encrypted). PersonalNameAttributeConverter SSOT. length>=512 per PII_PROTECTION_STANDARD §6.',
  `nickname` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PII (AES-256/CBC encrypted). PersonalNameAttributeConverter SSOT. length>=512 per PII_PROTECTION_STANDARD §6.',
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `password` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_reset_expires_at` datetime(6) DEFAULT NULL,
  `password_reset_token` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PII (AES-256/CBC encrypted). PhoneAttributeConverter SSOT. length>=512 per PII_PROTECTION_STANDARD §6.',
  `postal_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `profile_image` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `qualifications` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `role` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `professional_provider_type_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PROFESSIONAL_PROVIDER_TYPE code_value',
  `counseling_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'ADMIN 상담 겸직',
  `specialization` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `total_consultations` int DEFAULT NULL,
  `user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `profile_image_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Profile image URL only (no base64 dataURI). Max 500 chars (V20260609_002).',
  `age` int DEFAULT NULL,
  `is_social_account` bit(1) NOT NULL,
  `social_linked_at` datetime(6) DEFAULT NULL,
  `social_provider` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `social_provider_user_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `apple_sub` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Apple Sign in with Apple subject identifier (identityToken sub). NULLABLE — Apple 미사용 사용자(카카오/네이버/이메일)는 NULL. T1 Apple 4.8 대응 (Flyway V20260607_009).',
  `branch_id` bigint DEFAULT NULL,
  `branch_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auto_reminder` bit(1) DEFAULT NULL,
  `data_sharing` bit(1) DEFAULT NULL,
  `email_notification` bit(1) DEFAULT NULL,
  `preferred_session_duration` int DEFAULT NULL,
  `profile_visibility` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `push_notification` bit(1) DEFAULT NULL,
  `sms_notification` bit(1) DEFAULT NULL,
  `kakao_alimtalk_notification` bit(1) DEFAULT NULL,
  `notification_preferences` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `specialty` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `custom_theme_colors` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `theme_preference` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tenant_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '테넌트 ID',
  `is_password_changed` tinyint(1) NOT NULL DEFAULT '1' COMMENT '비밀번호 변경 여부 (임시 비밀번호인 경우 false, 비밀번호 변경 후 true)',
  `rrn_encrypted` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '주민번호 암호화값(앞6+뒤1)',
  `notification_channel_preference` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'TENANT_DEFAULT',
  `lifecycle_state` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE' COMMENT 'SSOT 회원 lifecycle 단계 — ACTIVE / SUSPENDED / WITHDRAWAL_PENDING / DORMANT / ANONYMIZED / DELETED_BY_ADMIN / HARD_DELETED (USER_LIFECYCLE_TERMINATION_POLICY §3.6)',
  `withdrawal_requested_at` timestamp NULL DEFAULT NULL COMMENT 'WITHDRAWAL_PENDING 진입 시각 — 30일 유예 만료 검색용 (Q3 결정)',
  `withdrawal_options_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '자발 탈퇴 본인 옵션 JSON (Q12-b 등). WITHDRAWAL_PENDING 진입 시 직렬화, ANONYMIZED 전이 시 사용',
  `deleted_by_admin_id` bigint DEFAULT NULL COMMENT '어드민 강제 종료(DELETED_BY_ADMIN) 시점에 강제 종료를 수행한 어드민 users.id — 7일 보존 윈도우 조회 + audit 보강 (USER_LIFECYCLE_TERMINATION_POLICY §0.1 Q5)',
  `past_session_count` bigint DEFAULT NULL COMMENT '과거 회기수 (외부 상담 이력, NULL=신규 내담자, 0=명시적 0회)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_r43af9ap4edm43mmtq01oddj6` (`user_id`),
  UNIQUE KEY `UK_users_user_id` (`user_id`),
  UNIQUE KEY `UK_users_email_tenant` (`email`,`tenant_id`),
  UNIQUE KEY `uk_users_apple_sub` (`apple_sub`),
  KEY `idx_users_username` (`user_id`),
  KEY `idx_users_email` (`email`),
  KEY `idx_users_phone` (`phone`),
  KEY `idx_users_role` (`role`),
  KEY `idx_users_grade` (`grade`),
  KEY `idx_users_is_deleted` (`is_deleted`),
  KEY `FK9o70sp9ku40077y38fk4wieyk` (`branch_id`),
  KEY `idx_users_tenant_id` (`tenant_id`),
  KEY `idx_users_tenant_branch` (`tenant_id`,`branch_id`),
  KEY `idx_users_tenant_role` (`tenant_id`,`role`),
  KEY `idx_users_tenant_active` (`tenant_id`,`is_active`,`is_deleted`),
  KEY `idx_users_tenant_role_active` (`tenant_id`,`role`,`is_active`),
  KEY `idx_users_tenant_email` (`tenant_id`,`email`),
  KEY `idx_users_lifecycle_state` (`tenant_id`,`lifecycle_state`),
  KEY `idx_users_withdrawal_pending` (`lifecycle_state`,`withdrawal_requested_at`),
  KEY `idx_users_deleted_by_admin` (`deleted_by_admin_id`),
  KEY `idx_users_deleted_admin_window` (`lifecycle_state`,`deleted_at`),
  KEY `idx_users_last_login_lifecycle` (`last_login_at`,`lifecycle_state`),
  KEY `idx_users_tenant_role_deleted` (`tenant_id`,`role`,`is_deleted`),
  CONSTRAINT `FK9o70sp9ku40077y38fk4wieyk` FOREIGN KEY (`branch_id`) REFERENCES `branches_dropped_20260612` (`id`),
  CONSTRAINT `fk_users_deleted_by_admin` FOREIGN KEY (`deleted_by_admin_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;
