-- source: dev DB (production D-1 copy), 2026-10-05
-- AUTO_INCREMENT start values and DEFINER removed. Columns, lengths, and constraints are unchanged.
-- queried_at: 2026-10-05 14:44:43 KST
CREATE TABLE `consultants` (
  `average_rating` double DEFAULT NULL,
  `awards_achievements` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `break_between_sessions` int DEFAULT NULL,
  `break_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `certification` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `consultation_hours` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `current_clients` int DEFAULT NULL,
  `education` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `is_available` bit(1) DEFAULT NULL,
  `is_supervisor` bit(1) DEFAULT NULL,
  `last_consultation_date` date DEFAULT NULL,
  `max_clients` int DEFAULT NULL,
  `next_available_date` date DEFAULT NULL,
  `preferred_consultation_methods` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `professional_background` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `research_publications` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `session_duration` int DEFAULT NULL,
  `specialty` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `specialty_details` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `success_rate` double DEFAULT NULL,
  `supervision_required` bit(1) DEFAULT NULL,
  `supervisor_id` bigint DEFAULT NULL,
  `total_clients` int DEFAULT NULL,
  `total_ratings` int DEFAULT NULL,
  `work_history` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `years_of_experience` int DEFAULT NULL,
  `id` bigint NOT NULL,
  `tenant_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '테넌트 UUID',
  `is_deleted` tinyint(1) DEFAULT '0',
  `grade` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'CONSULTANT',
  `lang_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'ko' COMMENT '언어 코드',
  `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '생성자',
  `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '수정자',
  `vehicle_plate` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '차량번호(선택)',
  PRIMARY KEY (`id`),
  KEY `idx_consultants_specialty` (`specialty`),
  KEY `idx_consultants_is_deleted` (`is_deleted`),
  KEY `idx_consultants_grade` (`grade`),
  KEY `idx_consultants_tenant_id` (`tenant_id`),
  KEY `idx_consultants_tenant_active` (`tenant_id`,`is_deleted`),
  CONSTRAINT `FKr01523mxgyc6q96skwno14yy9` FOREIGN KEY (`id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;
