package com.coresolution.consultation.service.impl;

import com.coresolution.consultation.entity.AudioTranscription;
import com.coresolution.consultation.entity.ClinicalReport;
import com.coresolution.consultation.entity.ConsultationRecord;
import com.coresolution.consultation.repository.ClinicalReportRepository;
import com.coresolution.consultation.repository.ConsultationRecordRepository;
import com.coresolution.consultation.service.ClinicalDocumentService;
import com.coresolution.core.context.TenantContextHolder;
import com.coresolution.core.service.ai.AIModelProvider;
import com.coresolution.core.service.ai.AIModelProvider.AIResponse;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;

/**
 * 임상 문서 자동 생성 서비스 구현체
 * Google Gemini Pro를 활용한 SOAP/DAP 노트 및 진단 보고서 생성
 *
 * @author MindGarden
 * @version 1.0.0
 * @since 2026-01-21
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ClinicalDocumentServiceImpl implements ClinicalDocumentService {

    private final AIModelProvider geminiModelProvider;
    private final ClinicalReportRepository clinicalReportRepository;
    private final ConsultationRecordRepository consultationRecordRepository;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Override
    @Transactional
    public ClinicalReport generateSOAPNote(AudioTranscription transcription, ConsultationRecord record) {
        long startTime = System.currentTimeMillis();

        try {
            log.info("📝 SOAP 노트 생성 시작: recordId={}", record.getId());

            // 시스템 프롬프트
            String systemPrompt = getClinicalExpertSystemPrompt();

            // 사용자 프롬프트
            String userPrompt = buildSOAPPrompt(transcription, record);

            // Gemini API 호출
            AIResponse aiResponse = geminiModelProvider.analyze(
                systemPrompt, userPrompt, 2000, 0.3);

            if (!aiResponse.isSuccess()) {
                log.error("❌ Gemini API 호출 실패: {}", aiResponse.getErrorMessage());
                throw new RuntimeException("AI 분석 실패: " + aiResponse.getErrorMessage());
            }

            long processingTime = System.currentTimeMillis() - startTime;

            // JSON 응답 파싱
            SOAPSections sections = parseSOAPResponse(aiResponse.getContent());

            // 보고서 엔티티 생성
            ClinicalReport report = ClinicalReport.builder()
                .consultationRecordId(record.getId())
                .reportType("SOAP")
                .reportFormat("SOAP")
                .subjectiveText(sections.subjective)
                .objectiveText(sections.objective)
                .assessmentText(sections.assessment)
                .planText(sections.plan)
                .autoGenerated(true)
                .humanReviewed(false)
                .aiModelUsed(geminiModelProvider.getModelName())
                .generationTimeMs((int) processingTime)
                .confidenceScore(calculateConfidenceScore(sections))
                .build();

            report.setTenantId(record.getTenantId());

            report = clinicalReportRepository.save(report);

            log.info("✅ SOAP 노트 생성 완료: reportId={}, time={}ms", report.getId(), processingTime);

            return report;

        } catch (Exception e) {
            log.error("❌ SOAP 노트 생성 실패: recordId={}, error={}",
                record.getId(), e.getMessage(), e);
            throw new RuntimeException("SOAP 노트 생성 실패: " + e.getMessage(), e);
        }
    }

    @Override
    @Transactional
    public ClinicalReport generateDAPNote(AudioTranscription transcription, ConsultationRecord record) {
        long startTime = System.currentTimeMillis();

        try {
            log.info("📝 DAP 노트 생성 시작: recordId={}", record.getId());

            String systemPrompt = getClinicalExpertSystemPrompt();
            String userPrompt = buildDAPPrompt(transcription, record);

            AIResponse aiResponse = geminiModelProvider.analyze(
                systemPrompt, userPrompt, 2000, 0.3);

            if (!aiResponse.isSuccess()) {
                throw new RuntimeException("AI 분석 실패: " + aiResponse.getErrorMessage());
            }

            long processingTime = System.currentTimeMillis() - startTime;

            // JSON 응답 파싱
            DAPSections sections = parseDAPResponse(aiResponse.getContent());

            ClinicalReport report = ClinicalReport.builder()
                .consultationRecordId(record.getId())
                .reportType("DAP")
                .reportFormat("DAP")
                .dataText(sections.data)
                .assessmentText(sections.assessment)
                .planText(sections.plan)
                .autoGenerated(true)
                .humanReviewed(false)
                .aiModelUsed(geminiModelProvider.getModelName())
                .generationTimeMs((int) processingTime)
                .build();

            report.setTenantId(record.getTenantId());

            report = clinicalReportRepository.save(report);

            log.info("✅ DAP 노트 생성 완료: reportId={}, time={}ms", report.getId(), processingTime);

            return report;

        } catch (Exception e) {
            log.error("❌ DAP 노트 생성 실패: recordId={}, error={}",
                record.getId(), e.getMessage(), e);
            throw new RuntimeException("DAP 노트 생성 실패: " + e.getMessage(), e);
        }
    }

    @Override
    @Transactional
    public ClinicalReport generateDiagnosticReport(Long consultationRecordId) {
        long startTime = System.currentTimeMillis();

        try {
            log.info("📋 진단 보고서 생성 시작: recordId={}", consultationRecordId);
            String tenantId = TenantContextHolder.getRequiredTenantId();
            ConsultationRecord record = consultationRecordRepository.findByTenantIdAndId(tenantId, consultationRecordId)
                .orElseThrow(() -> new IllegalArgumentException("상담 기록을 찾을 수 없습니다."));

            String systemPrompt = getDiagnosticExpertSystemPrompt();
            String userPrompt = buildDiagnosticReportPrompt(record);

            AIResponse aiResponse = geminiModelProvider.analyze(
                systemPrompt, userPrompt, 3000, 0.2); // 진단은 보수적으로 (낮은 temperature)

            if (!aiResponse.isSuccess()) {
                throw new RuntimeException("AI 분석 실패: " + aiResponse.getErrorMessage());
            }

            long processingTime = System.currentTimeMillis() - startTime;

            // JSON 응답 파싱
            DiagnosticSections sections = parseDiagnosticResponse(aiResponse.getContent());

            ClinicalReport report = ClinicalReport.builder()
                .consultationRecordId(consultationRecordId)
                .reportType("DIAGNOSTIC")
                .reportFormat("DIAGNOSTIC")
                .diagnosisSummary(sections.summary)
                .diagnosticImpressions(sections.impressions)
                .treatmentRecommendations(sections.recommendations)
                .autoGenerated(true)
                .humanReviewed(false)
                .aiModelUsed(geminiModelProvider.getModelName())
                .generationTimeMs((int) processingTime)
                .build();

            report.setTenantId(record.getTenantId());

            report = clinicalReportRepository.save(report);

            log.info("✅ 진단 보고서 생성 완료: reportId={}, time={}ms", report.getId(), processingTime);

            return report;

        } catch (Exception e) {
            log.error("❌ 진단 보고서 생성 실패: recordId={}, error={}",
                consultationRecordId, e.getMessage(), e);
            throw new RuntimeException("진단 보고서 생성 실패: " + e.getMessage(), e);
        }
    }

    @Override
    public ClinicalReport getClinicalReport(Long reportId) {
        return clinicalReportRepository.findByIdAndIsDeletedFalse(reportId)
            .orElseThrow(() -> new IllegalArgumentException("임상 보고서를 찾을 수 없습니다: " + reportId));
    }

    @Override
    @Transactional
    public ClinicalReport updateClinicalReport(Long reportId, ClinicalReport updatedReport) {
        ClinicalReport report = getClinicalReport(reportId);

        // 업데이트 가능한 필드만 수정
        if (updatedReport.getSubjectiveText() != null) {
            report.setSubjectiveText(updatedReport.getSubjectiveText());
        }
        if (updatedReport.getObjectiveText() != null) {
            report.setObjectiveText(updatedReport.getObjectiveText());
        }
        if (updatedReport.getAssessmentText() != null) {
            report.setAssessmentText(updatedReport.getAssessmentText());
        }
        if (updatedReport.getPlanText() != null) {
            report.setPlanText(updatedReport.getPlanText());
        }
        if (updatedReport.getDataText() != null) {
            report.setDataText(updatedReport.getDataText());
        }
        if (updatedReport.getDiagnosisSummary() != null) {
            report.setDiagnosisSummary(updatedReport.getDiagnosisSummary());
        }
        if (updatedReport.getDiagnosticImpressions() != null) {
            report.setDiagnosticImpressions(updatedReport.getDiagnosticImpressions());
        }
        if (updatedReport.getTreatmentRecommendations() != null) {
            report.setTreatmentRecommendations(updatedReport.getTreatmentRecommendations());
        }

        return clinicalReportRepository.save(report);
    }

    @Override
    @Transactional
    public ClinicalReport approveClinicalReport(Long reportId, Long reviewerUserId) {
        ClinicalReport report = getClinicalReport(reportId);
        report.markAsReviewed(reviewerUserId);
        return clinicalReportRepository.save(report);
    }

    // ==================== Private Helper Methods ====================

    /**
     * 임상 전문가 시스템 프롬프트
     */
    private String getClinicalExpertSystemPrompt() {
        return "당신은 대한민국의 전문 상담심리사입니다. " +
               "15년 이상의 임상 경험을 가지고 있으며, " +
               "정확하고 전문적인 임상 기록을 작성하는 데 능숙합니다. " +
               "내담자의 안전과 프라이버시를 최우선으로 고려하며, " +
               "윤리적이고 책임감 있는 상담 기록을 작성합니다.";
    }

    /**
     * 진단 전문가 시스템 프롬프트
     */
    private String getDiagnosticExpertSystemPrompt() {
        return "당신은 대한민국의 임상심리 전문가입니다. " +
               "DSM-5와 ICD-11을 기반으로 정확한 진단적 평가를 수행하며, " +
               "내담자의 증상, 행동 패턴, 심리 검사 결과를 종합적으로 분석합니다. " +
               "확정적인 진단보다는 임상적 인상과 관찰 사항을 중심으로 작성하며, " +
               "근거 기반 치료 권고사항을 제시합니다.";
    }

    /**
     * SOAP 노트 생성 프롬프트 구성
     */
    private String buildSOAPPrompt(AudioTranscription transcription, ConsultationRecord record) {
        return String.format(
            "다음 상담 대화 전사 내용을 SOAP 형식으로 정리해주세요.\n\n" +
            "[전사 내용]\n%s\n\n" +
            "[상담 정보]\n" +
            "- 세션 번호: %d회차\n" +
            "- 상담 일자: %s\n" +
            "- 세션 시간: %d분\n\n" +
            "[작성 지침]\n" +
            "다음 4개 섹션으로 구조화하여 JSON 형식으로 반환해주세요:\n\n" +
            "1. Subjective (주관적 정보):\n" +
            "   - 내담자가 직접 보고한 증상, 감정, 생각\n" +
            "   - \"내담자는 ~라고 말했다\" 형식\n" +
            "   - 200-400자\n\n" +
            "2. Objective (객관적 정보):\n" +
            "   - 상담사가 관찰한 행동, 외모, 태도\n" +
            "   - \"관찰됨: ~\" 형식\n" +
            "   - 150-300자\n\n" +
            "3. Assessment (평가):\n" +
            "   - 임상적 인상 및 진단적 고려사항\n" +
            "   - DSM-5/ICD-11 기준 참고\n" +
            "   - 200-400자\n\n" +
            "4. Plan (계획):\n" +
            "   - 치료 계획 및 다음 세션 목표\n" +
            "   - 과제 부여 사항\n" +
            "   - 150-300자\n\n" +
            "응답 형식 (JSON):\n" +
            "{\n" +
            "  \"subjective\": \"주관적 정보 텍스트\",\n" +
            "  \"objective\": \"객관적 정보 텍스트\",\n" +
            "  \"assessment\": \"평가 텍스트\",\n" +
            "  \"plan\": \"계획 텍스트\"\n" +
            "}\n\n" +
            "⚠️ 중요:\n" +
            "- 반드시 한국어로 작성\n" +
            "- 전문 용어는 한글 표기 우선 (필요시 영문 병기)\n" +
            "- 확정적 진단은 피하고 '~로 보임', '~가능성' 등 신중한 표현 사용\n" +
            "- JSON 형식 준수 (다른 텍스트 포함 금지)",
            transcription.getTranscriptionText(),
            record.getSessionNumber() != null ? record.getSessionNumber() : 1,
            record.getSessionDate(),
            record.getSessionDurationMinutes() != null ? record.getSessionDurationMinutes() : 60
        );
    }

    /**
     * DAP 노트 생성 프롬프트 구성
     */
    private String buildDAPPrompt(AudioTranscription transcription, ConsultationRecord record) {
        return String.format(
            "다음 상담 대화 전사 내용을 DAP 형식으로 정리해주세요.\n\n" +
            "[전사 내용]\n%s\n\n" +
            "[상담 정보]\n" +
            "- 세션 번호: %d회차\n" +
            "- 상담 일자: %s\n\n" +
            "[작성 지침]\n" +
            "다음 3개 섹션으로 구조화하여 JSON 형식으로 반환해주세요:\n\n" +
            "1. Data (데이터):\n" +
            "   - 객관적 관찰 + 내담자 보고 통합\n" +
            "   - 300-500자\n\n" +
            "2. Assessment (평가):\n" +
            "   - 임상적 평가 및 분석\n" +
            "   - 200-400자\n\n" +
            "3. Plan (계획):\n" +
            "   - 치료 계획 및 목표\n" +
            "   - 150-300자\n\n" +
            "응답 형식 (JSON):\n" +
            "{\n" +
            "  \"data\": \"데이터 텍스트\",\n" +
            "  \"assessment\": \"평가 텍스트\",\n" +
            "  \"plan\": \"계획 텍스트\"\n" +
            "}",
            transcription.getTranscriptionText(),
            record.getSessionNumber() != null ? record.getSessionNumber() : 1,
            record.getSessionDate()
        );
    }

    /**
     * 진단 보고서 생성 프롬프트 구성
     */
    private String buildDiagnosticReportPrompt(ConsultationRecord record) {
        return String.format(
            "다음 상담 기록을 바탕으로 진단 보고서 초안을 작성해주세요.\n\n" +
            "[상담 정보]\n" +
            "- 세션 번호: %d회차\n" +
            "- 내담자 상태: %s\n" +
            "- 주요 이슈: %s\n" +
            "- 개입 방법: %s\n" +
            "- 내담자 반응: %s\n" +
            "- 위험도: %s\n" +
            "- 진행도 점수: %d/100\n\n" +
            "[작성 지침]\n" +
            "다음 3개 섹션으로 구조화하여 JSON 형식으로 반환해주세요:\n\n" +
            "1. 진단 요약 (summary): 300-500자\n" +
            "2. 진단적 인상 (impressions): 400-600자\n" +
            "3. 치료 권고사항 (recommendations): 300-500자\n\n" +
            "응답 형식 (JSON):\n" +
            "{\n" +
            "  \"summary\": \"진단 요약\",\n" +
            "  \"impressions\": \"진단적 인상\",\n" +
            "  \"recommendations\": \"치료 권고사항\"\n" +
            "}",
            record.getSessionNumber() != null ? record.getSessionNumber() : 1,
            record.getClientCondition() != null ? record.getClientCondition() : "기록 없음",
            record.getMainIssues() != null ? record.getMainIssues() : "기록 없음",
            record.getInterventionMethods() != null ? record.getInterventionMethods() : "기록 없음",
            record.getClientResponse() != null ? record.getClientResponse() : "기록 없음",
            record.getRiskAssessment() != null ? record.getRiskAssessment() : "LOW",
            record.getProgressScore() != null ? record.getProgressScore() : 0
        );
    }

    /**
     * SOAP 응답 파싱
     */
    private SOAPSections parseSOAPResponse(String jsonResponse) {
        try {
            // JSON 코드 블록 제거
            String cleanJson = cleanJsonResponse(jsonResponse);

            JsonNode root = objectMapper.readTree(cleanJson);

            return new SOAPSections(
                root.path("subjective").asText(""),
                root.path("objective").asText(""),
                root.path("assessment").asText(""),
                root.path("plan").asText("")
            );
        } catch (Exception e) {
            log.error("SOAP 응답 파싱 실패: {}", jsonResponse, e);
            throw new RuntimeException("SOAP 응답 파싱 실패", e);
        }
    }

    /**
     * DAP 응답 파싱
     */
    private DAPSections parseDAPResponse(String jsonResponse) {
        try {
            String cleanJson = cleanJsonResponse(jsonResponse);
            JsonNode root = objectMapper.readTree(cleanJson);

            return new DAPSections(
                root.path("data").asText(""),
                root.path("assessment").asText(""),
                root.path("plan").asText("")
            );
        } catch (Exception e) {
            log.error("DAP 응답 파싱 실패: {}", jsonResponse, e);
            throw new RuntimeException("DAP 응답 파싱 실패", e);
        }
    }

    /**
     * 진단 응답 파싱
     */
    private DiagnosticSections parseDiagnosticResponse(String jsonResponse) {
        try {
            String cleanJson = cleanJsonResponse(jsonResponse);
            JsonNode root = objectMapper.readTree(cleanJson);

            return new DiagnosticSections(
                root.path("summary").asText(""),
                root.path("impressions").asText(""),
                root.path("recommendations").asText("")
            );
        } catch (Exception e) {
            log.error("진단 보고서 응답 파싱 실패: {}", jsonResponse, e);
            throw new RuntimeException("진단 보고서 응답 파싱 실패", e);
        }
    }

    /**
     * JSON 응답 정리 (코드 블록 제거)
     */
    private String cleanJsonResponse(String response) {
        response = response.trim();
        if (response.startsWith("```json")) {
            response = response.substring(7);
        }
        if (response.startsWith("```")) {
            response = response.substring(3);
        }
        if (response.endsWith("```")) {
            response = response.substring(0, response.length() - 3);
        }
        return response.trim();
    }

    /**
     * SOAP 노트 신뢰도 점수 계산
     */
    private BigDecimal calculateConfidenceScore(SOAPSections sections) {
        int filledSections = 0;
        int totalLength = 0;

        if (sections.subjective != null && !sections.subjective.isEmpty()) {
            filledSections++;
            totalLength += sections.subjective.length();
        }
        if (sections.objective != null && !sections.objective.isEmpty()) {
            filledSections++;
            totalLength += sections.objective.length();
        }
        if (sections.assessment != null && !sections.assessment.isEmpty()) {
            filledSections++;
            totalLength += sections.assessment.length();
        }
        if (sections.plan != null && !sections.plan.isEmpty()) {
            filledSections++;
            totalLength += sections.plan.length();
        }

        // 완성도 기반 점수 (모든 섹션이 채워지고 적절한 길이면 높은 점수)
        double completionScore = (filledSections * 100.0) / 4.0;
        double lengthScore = Math.min(totalLength / 10.0, 100.0); // 1000자면 100점

        double finalScore = (completionScore * 0.7) + (lengthScore * 0.3);

        return BigDecimal.valueOf(Math.min(finalScore, 100.0))
            .setScale(2, java.math.RoundingMode.HALF_UP);
    }

    // DTO classes
    private static class SOAPSections {
        String subjective;
        String objective;
        String assessment;
        String plan;

        SOAPSections(String subjective, String objective, String assessment, String plan) {
            this.subjective = subjective;
            this.objective = objective;
            this.assessment = assessment;
            this.plan = plan;
        }
    }

    private static class DAPSections {
        String data;
        String assessment;
        String plan;

        DAPSections(String data, String assessment, String plan) {
            this.data = data;
            this.assessment = assessment;
            this.plan = plan;
        }
    }

    private static class DiagnosticSections {
        String summary;
        String impressions;
        String recommendations;

        DiagnosticSections(String summary, String impressions, String recommendations) {
            this.summary = summary;
            this.impressions = impressions;
            this.recommendations = recommendations;
        }
    }
}
