#!/bin/bash
# acme-dns 기반 와일드카드 SSL 발급 래퍼 (Phase C 사용 대비)
#
# 설계서: docs/project-management/2026-05-28/SSL_WILDCARD_ACMEDNS_AUTO_RENEW_HANDOFF.md
# 기존 issue-wildcard-ssl-prod.sh / issue-wildcard-ssl-dev.sh 의 무인 대체.
#
# 사용법:
#   sudo ./issue-wildcard-ssl-via-acmedns.sh <root-domain> [--email <email>] [--force] [--dry-run]
# 예:
#   sudo ./issue-wildcard-ssl-via-acmedns.sh core-solution.co.kr
#   sudo ./issue-wildcard-ssl-via-acmedns.sh dev.core-solution.co.kr --email admin@e-trinity.co.kr
#   sudo ./issue-wildcard-ssl-via-acmedns.sh core-solution.co.kr --dry-run
#
# 사전 조건:
#   1) acme-dns systemd active (install-acme-dns.sh 완료)
#   2) register-acme-dns-domain.sh <root-domain> 완료 → /etc/letsencrypt/acmedns.json 항목 존재
#   3) 가비아 CNAME 등록 + 전파 완료 (Phase B)
#   4) certbot + certbot-dns-acmedns 플러그인 설치 (pip3 install certbot-dns-acmedns)
#
# 자격증명 파일 구조 (pan-net-security/certbot-dns-acmedns 0.1.0 호환):
#   - INI: /etc/letsencrypt/acmedns.ini  (certbot 에 직접 전달)
#       dns_acmedns_api_url             = http://127.0.0.1:8053
#       dns_acmedns_registration_file   = /etc/letsencrypt/acmedns.json
#   - JSON: /etc/letsencrypt/acmedns.json (도메인↔acme-dns 자격 매핑, register-acme-dns-domain.sh 가 관리)
#   본 스크립트는 INI 가 없으면 JSON 기반으로 자동 생성한다 (Phase C 정합 보강).

set -euo pipefail

readonly ACMEDNS_REGISTRATION="${ACMEDNS_REGISTRATION:-/etc/letsencrypt/acmedns.json}"
readonly ACMEDNS_INI="${ACMEDNS_INI:-/etc/letsencrypt/acmedns.ini}"
readonly ACMEDNS_API_URL="${ACMEDNS_API_URL:-http://127.0.0.1:8053}"
readonly DEFAULT_EMAIL="${ACME_DNS_EMAIL:-admin@e-trinity.co.kr}"
readonly LOG_PREFIX="[issue-wildcard-ssl-via-acmedns]"

DRY_RUN=0
FORCE=0
EMAIL="${DEFAULT_EMAIL}"
ROOT_DOMAIN=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run) DRY_RUN=1; shift ;;
        --force)   FORCE=1; shift ;;
        --email)   EMAIL="$2"; shift 2 ;;
        -h|--help)
            grep '^#' "$0" | head -25
            exit 0
            ;;
        --*)
            echo "${LOG_PREFIX} 알 수 없는 옵션: $1" >&2
            exit 2
            ;;
        *)
            if [[ -z "${ROOT_DOMAIN}" ]]; then
                ROOT_DOMAIN="$1"
            else
                echo "${LOG_PREFIX} 도메인 인자는 1개만 허용됩니다." >&2
                exit 2
            fi
            shift
            ;;
    esac
done

if [[ -z "${ROOT_DOMAIN}" ]]; then
    echo "${LOG_PREFIX} 사용법: $0 <root-domain> [--email <email>] [--force] [--dry-run]" >&2
    exit 2
fi

log() { echo "${LOG_PREFIX} $*"; }

if [[ "${DRY_RUN}" -eq 0 && "$(id -u)" -ne 0 ]]; then
    echo "${LOG_PREFIX} root 권한 필요 (sudo)." >&2
    exit 1
fi

# ===== 사전 점검 =====
log "사전 점검..."
if ! command -v certbot >/dev/null 2>&1; then
    echo "${LOG_PREFIX} certbot 미설치. apt-get install -y certbot 후 재실행." >&2
    [[ "${DRY_RUN}" -eq 0 ]] && exit 1
fi

PLUGIN_OK=0
if command -v certbot >/dev/null 2>&1; then
    if certbot plugins 2>/dev/null | grep -q "dns-acmedns"; then
        PLUGIN_OK=1
    fi
fi
if [[ "${PLUGIN_OK}" -eq 0 ]]; then
    echo "${LOG_PREFIX} certbot-dns-acmedns 플러그인 미설치." >&2
    echo "${LOG_PREFIX}   설치: pip3 install certbot-dns-acmedns" >&2
    [[ "${DRY_RUN}" -eq 0 ]] && exit 1
fi

if [[ ! -f "${ACMEDNS_REGISTRATION}" ]]; then
    echo "${LOG_PREFIX} 등록 파일 ${ACMEDNS_REGISTRATION} 미존재. register-acme-dns-domain.sh ${ROOT_DOMAIN} 먼저 실행." >&2
    [[ "${DRY_RUN}" -eq 0 ]] && exit 1
fi

if [[ "${DRY_RUN}" -eq 0 ]] && command -v jq >/dev/null 2>&1; then
    if ! jq -e --arg d "${ROOT_DOMAIN}" '.[$d]' "${ACMEDNS_REGISTRATION}" >/dev/null 2>&1; then
        echo "${LOG_PREFIX} ${ACMEDNS_REGISTRATION} 에 ${ROOT_DOMAIN} 항목 없음. register-acme-dns-domain.sh ${ROOT_DOMAIN} 먼저 실행." >&2
        exit 1
    fi
fi

# ===== INI 자격증명 파일 보강 (멱등) =====
# pan-net-security/certbot-dns-acmedns 0.1.0 은 INI 형식의 credentials 를 요구한다.
# INI 가 없으면 JSON 등록 파일 + 기본 API URL 로 생성한다.
if [[ ! -f "${ACMEDNS_INI}" ]]; then
    log "INI 자격증명 미존재 → 생성: ${ACMEDNS_INI}"
    if [[ "${DRY_RUN}" -eq 0 ]]; then
        umask 077
        cat > "${ACMEDNS_INI}" <<EOF
# certbot-dns-acmedns INI credentials (auto-generated by issue-wildcard-ssl-via-acmedns.sh)
# 설계서: docs/project-management/2026-05-28/SSL_WILDCARD_ACMEDNS_AUTO_RENEW_HANDOFF.md
dns_acmedns_api_url           = ${ACMEDNS_API_URL}
dns_acmedns_registration_file = ${ACMEDNS_REGISTRATION}
EOF
        chown root:root "${ACMEDNS_INI}"
        chmod 0600 "${ACMEDNS_INI}"
    else
        log "[dry-run] INI 생성 생략 (ACMEDNS_API_URL=${ACMEDNS_API_URL})"
    fi
else
    log "INI 자격증명 재사용: ${ACMEDNS_INI}"
fi

# 권한 보호: certbot 플러그인이 perm 검증을 수행 (root:root 0600 권장)
if [[ "${DRY_RUN}" -eq 0 ]]; then
    chmod 0600 "${ACMEDNS_INI}" "${ACMEDNS_REGISTRATION}" 2>/dev/null || true
fi

# ===== CNAME 전파 확인 (read-only, dry-run 에서도 수행) =====
CHALLENGE_NAME="_acme-challenge.${ROOT_DOMAIN}"
CNAME_RESULT=""
log "CNAME 전파 확인: dig CNAME ${CHALLENGE_NAME} @8.8.8.8 +short"
if command -v dig >/dev/null 2>&1; then
    CNAME_RESULT="$(dig CNAME "${CHALLENGE_NAME}" @8.8.8.8 +short 2>/dev/null || true)"
    if [[ -z "${CNAME_RESULT}" ]]; then
        echo "${LOG_PREFIX} ⚠️  ${CHALLENGE_NAME} CNAME 미전파. 가비아 등록 + 5-10분 대기 후 재실행." >&2
        if [[ "${DRY_RUN}" -eq 0 && "${FORCE}" -ne 1 ]]; then
            echo "${LOG_PREFIX} 강제 진행: --force 옵션 사용" >&2
            exit 1
        fi
    else
        log "   ✅ ${CHALLENGE_NAME} → ${CNAME_RESULT}"
    fi
fi

# ===== NS 위임 사전 점검 (Phase B 누락 검출, dry-run 에서도 수행) =====
# CNAME 만 있고 acme-dns 서비스 도메인의 NS 위임이 없으면 LE 검증 실패한다 (No TXT record found).
# 부모 zone (예: core-solution.co.kr) 의 권한 NS 가 acme 서브도메인을 acme-dns 서버로 위임해야 한다.
if command -v dig >/dev/null 2>&1 && [[ -n "${CNAME_RESULT}" ]]; then
    # CNAME 결과에서 fulldomain (예: <uuid>.acme.core-solution.co.kr.) 추출하여 acme zone 확인
    ACME_FULLDOMAIN="${CNAME_RESULT%.}"
    # acme zone = fulldomain 의 첫 라벨을 제거 (e.g., uuid.acme.core-solution.co.kr → acme.core-solution.co.kr)
    ACME_ZONE="${ACME_FULLDOMAIN#*.}"
    log "NS 위임 점검: dig NS ${ACME_ZONE} @8.8.8.8 +short"
    NS_RESULT="$(dig NS "${ACME_ZONE}" @8.8.8.8 +short 2>/dev/null || true)"
    if [[ -z "${NS_RESULT}" ]]; then
        echo "${LOG_PREFIX} ❌ ${ACME_ZONE} 에 NS 위임 미설정 → LE 검증 실패 (No TXT record found)." >&2
        echo "${LOG_PREFIX}    조치 (가비아 DNS UI 1회):" >&2
        echo "${LOG_PREFIX}      레코드: ${ACME_ZONE}" >&2
        echo "${LOG_PREFIX}      타입  : NS" >&2
        echo "${LOG_PREFIX}      값    : ${ACME_ZONE}.   (글루: 동명 A 레코드 활용)" >&2
        echo "${LOG_PREFIX}    문서: docs/project-management/2026-05-28/SSL_WILDCARD_ACMEDNS_AUTO_RENEW_HANDOFF.md §6 Phase 2-B" >&2
        if [[ "${DRY_RUN}" -eq 0 && "${FORCE}" -ne 1 ]]; then
            exit 1
        fi
        log "⚠️  NS 위임 미설정 (dry-run 또는 --force) → 무시하고 진행 (실제 발급 시 실패)"
    else
        log "   ✅ ${ACME_ZONE} NS → $(echo "${NS_RESULT}" | tr '\n' ' ')"
    fi
fi

# ===== certbot 호출 =====
CERTBOT_ARGS=(
    certonly
    --non-interactive
    --agree-tos
    --email "${EMAIL}"
    --authenticator dns-acmedns
    --dns-acmedns-credentials "${ACMEDNS_INI}"
    --dns-acmedns-propagation-seconds 60
    -d "*.${ROOT_DOMAIN}"
    -d "${ROOT_DOMAIN}"
)

if [[ "${FORCE}" -eq 1 ]]; then
    CERTBOT_ARGS+=(--force-renewal)
fi

log "certbot 호출:"
log "  certbot ${CERTBOT_ARGS[*]}"

if [[ "${DRY_RUN}" -eq 1 ]]; then
    log "[dry-run] certbot 호출 생략"
    exit 0
fi

certbot "${CERTBOT_ARGS[@]}"

log ""
log "=== 발급 완료 ==="
log "  인증서 경로: /etc/letsencrypt/live/${ROOT_DOMAIN}/"
log "  fullchain  : /etc/letsencrypt/live/${ROOT_DOMAIN}/fullchain.pem"
log "  privkey    : /etc/letsencrypt/live/${ROOT_DOMAIN}/privkey.pem"
log ""
log "후속:"
log "  - nginx ssl_certificate 경로 확인 후 systemctl reload nginx"
log "  - 자동 갱신 검증: certbot renew --dry-run"
