#!/bin/bash
# acme-dns register API 호출 + 가비아 CNAME 가이드 출력 + 자격증명 누적 저장
#
# 설계서: docs/project-management/2026-05-28/SSL_WILDCARD_ACMEDNS_AUTO_RENEW_HANDOFF.md
# 사용법:
#   sudo ./register-acme-dns-domain.sh <domain>           # 예: core-solution.co.kr
#   sudo ./register-acme-dns-domain.sh <domain> --dry-run # 호출 없이 단계만 출력
#
# 동작:
#   - acme-dns API (http://127.0.0.1:8053/register) 호출 → username/password/fulldomain/subdomain 수신
#   - /etc/letsencrypt/acmedns.json 에 도메인별 키로 누적 저장 (jq merge)
#   - 멱등: 이미 등록된 도메인은 기존 자격 증명 그대로 반환 (acme-dns 자체가 도메인↔자격증명 mapping을 강제하지 않으므로 저장된 값 우선 사용)
#   - 가비아 CNAME 가이드 출력

set -euo pipefail

readonly ACME_DNS_API="${ACME_DNS_API:-http://127.0.0.1:8053}"
readonly ACMEDNS_CREDENTIALS="${ACMEDNS_CREDENTIALS:-/etc/letsencrypt/acmedns.json}"
readonly ACMEDNS_INI="${ACMEDNS_INI:-/etc/letsencrypt/acmedns.ini}"
readonly LOG_PREFIX="[register-acme-dns-domain]"
DRY_RUN=0
DOMAIN=""

# ===== 옵션 파싱 =====
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        -h|--help)
            grep '^#' "$0" | head -20
            exit 0
            ;;
        --*)
            echo "${LOG_PREFIX} 알 수 없는 옵션: $arg" >&2
            exit 2
            ;;
        *)
            if [[ -z "${DOMAIN}" ]]; then
                DOMAIN="$arg"
            else
                echo "${LOG_PREFIX} 도메인 인자는 1개만 허용됩니다." >&2
                exit 2
            fi
            ;;
    esac
done

if [[ -z "${DOMAIN}" ]]; then
    echo "${LOG_PREFIX} 사용법: $0 <domain> [--dry-run]" >&2
    exit 2
fi

log() { echo "${LOG_PREFIX} $*"; }

# ===== 사전 체크 =====
if [[ "${DRY_RUN}" -eq 0 && "$(id -u)" -ne 0 ]]; then
    echo "${LOG_PREFIX} root 권한 필요 (/etc/letsencrypt 쓰기)." >&2
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "${LOG_PREFIX} jq 미설치. 'apt-get install -y jq' 후 재실행." >&2
    [[ "${DRY_RUN}" -eq 0 ]] && exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
    echo "${LOG_PREFIX} curl 미설치." >&2
    exit 1
fi

log "도메인: ${DOMAIN}"
log "acme-dns API: ${ACME_DNS_API}/register"
log "자격증명 파일: ${ACMEDNS_CREDENTIALS}"

# ===== 기존 등록 확인 (멱등) =====
if [[ -f "${ACMEDNS_CREDENTIALS}" ]]; then
    if [[ "${DRY_RUN}" -eq 0 ]] && jq -e --arg d "${DOMAIN}" '.[$d]' "${ACMEDNS_CREDENTIALS}" >/dev/null 2>&1; then
        log "기존 자격증명 발견 → 재사용 (멱등)"
        EXISTING=$(jq --arg d "${DOMAIN}" '.[$d]' "${ACMEDNS_CREDENTIALS}")
        FULLDOMAIN=$(echo "${EXISTING}" | jq -r '.fulldomain')
        log ""
        log "=== 가비아 CNAME 가이드 (기존 등록) ==="
        log "  레코드: _acme-challenge.${DOMAIN}"
        log "  타입  : CNAME"
        log "  값    : ${FULLDOMAIN}."
        log "  TTL   : 600 (10분, 권장)"
        log ""
        echo "${EXISTING}" | jq .
        exit 0
    fi
fi

# ===== register 호출 =====
if [[ "${DRY_RUN}" -eq 1 ]]; then
    log "[dry-run] curl -X POST ${ACME_DNS_API}/register"
    log "[dry-run] 응답 예시: { \"username\": \"<uuid>\", \"password\": \"<...>\", \"fulldomain\": \"<uuid>.acme.core-solution.co.kr\", \"subdomain\": \"<uuid>\", \"allowfrom\": [] }"
    exit 0
fi

log "register API 호출 중..."
RESPONSE=$(curl -fsS -X POST -H "Content-Type: application/json" -d '{}' "${ACME_DNS_API}/register")
if [[ -z "${RESPONSE}" ]]; then
    echo "${LOG_PREFIX} 빈 응답. acme-dns 서비스 상태 확인." >&2
    exit 1
fi

USERNAME=$(echo "${RESPONSE}" | jq -r '.username')
PASSWORD=$(echo "${RESPONSE}" | jq -r '.password')
FULLDOMAIN=$(echo "${RESPONSE}" | jq -r '.fulldomain')
SUBDOMAIN=$(echo "${RESPONSE}" | jq -r '.subdomain')

if [[ -z "${USERNAME}" || "${USERNAME}" == "null" ]]; then
    echo "${LOG_PREFIX} register 응답 파싱 실패. 응답 원문:" >&2
    echo "${RESPONSE}" >&2
    exit 1
fi

# ===== 자격증명 누적 저장 =====
mkdir -p "$(dirname "${ACMEDNS_CREDENTIALS}")"
if [[ ! -f "${ACMEDNS_CREDENTIALS}" ]]; then
    echo '{}' > "${ACMEDNS_CREDENTIALS}"
    chmod 0600 "${ACMEDNS_CREDENTIALS}"
fi

NEW_ENTRY=$(jq -n \
    --arg u "${USERNAME}" \
    --arg p "${PASSWORD}" \
    --arg f "${FULLDOMAIN}" \
    --arg s "${SUBDOMAIN}" \
    '{username:$u, password:$p, fulldomain:$f, subdomain:$s, allowfrom:[]}')

MERGED=$(jq --arg d "${DOMAIN}" --argjson e "${NEW_ENTRY}" '. + {($d): $e}' "${ACMEDNS_CREDENTIALS}")
echo "${MERGED}" > "${ACMEDNS_CREDENTIALS}"
chown root:root "${ACMEDNS_CREDENTIALS}"
chmod 0600 "${ACMEDNS_CREDENTIALS}"

# ===== INI 자격증명 동기화 (Phase C 정합) =====
# pan-net-security/certbot-dns-acmedns 0.1.0 은 certbot --dns-acmedns-credentials 인자에
# INI 형식 파일을 요구하며, 그 INI 가 JSON 등록 파일 경로를 가리킨다.
# 따라서 register 단계에서 INI 가 없으면 함께 생성해 두어 발급 스크립트가 즉시 사용 가능하게 한다.
if [[ ! -f "${ACMEDNS_INI}" ]]; then
    log "INI 자격증명 미존재 → 생성: ${ACMEDNS_INI}"
    umask 077
    cat > "${ACMEDNS_INI}" <<EOF
# certbot-dns-acmedns INI credentials (auto-generated by register-acme-dns-domain.sh)
# 설계서: docs/project-management/2026-05-28/SSL_WILDCARD_ACMEDNS_AUTO_RENEW_HANDOFF.md
dns_acmedns_api_url           = ${ACME_DNS_API}
dns_acmedns_registration_file = ${ACMEDNS_CREDENTIALS}
EOF
    chown root:root "${ACMEDNS_INI}"
    chmod 0600 "${ACMEDNS_INI}"
fi

log ""
log "=== 등록 완료 ==="
log "  도메인       : ${DOMAIN}"
log "  username     : ${USERNAME}"
log "  fulldomain   : ${FULLDOMAIN}"
log "  subdomain    : ${SUBDOMAIN}"
log "  저장 위치    : ${ACMEDNS_CREDENTIALS}"
log ""
log "=== 가비아에 등록할 CNAME (Phase B 사용자 1회 작업) ==="
log "  레코드: _acme-challenge.${DOMAIN}"
log "  타입  : CNAME"
log "  값    : ${FULLDOMAIN}."
log "  TTL   : 600 (10분, 권장)"
log ""
log "전파 확인 (5~10분 후):"
log "  dig CNAME _acme-challenge.${DOMAIN} +short"
log "  → 결과가 '${FULLDOMAIN}.' 이면 OK"
