package com.coresolution.consultation.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

/**
 * 임상 보고서 엔티티 SOAP/DAP 형식의 임상 기록 및 진단 보고서
 *
 * @author MindGarden
 * @version 1.0.0
 * @since 2026-01-21
 */
@Entity
@Table(name = "clinical_reports",
        indexes = {
                @Index(name = "idx_consultation_record_id", columnList = "consultation_record_id"),
                @Index(name = "idx_tenant_id", columnList = "tenant_id"),
                @Index(name = "idx_report_type", columnList = "report_type"),
                @Index(name = "idx_human_reviewed", columnList = "human_reviewed"),
                @Index(name = "idx_created_at", columnList = "created_at")})
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
public class ClinicalReport extends BaseEntity {

    @NotNull(message = "상담 기록 ID는 필수입니다.")
    @Column(name = "consultation_record_id", nullable = false)
    private Long consultationRecordId;

    // 보고서 타입
    @NotNull(message = "보고서 타입은 필수입니다.")
    @Size(max = 50, message = "보고서 타입은 50자 이하여야 합니다.")
    @Column(name = "report_type", nullable = false, length = 50)
    private String reportType; // SOAP, DAP, DIAGNOSTIC

    @Size(max = 20, message = "보고서 형식은 20자 이하여야 합니다.")
    @Column(name = "report_format", length = 20)
    @Builder.Default
    private String reportFormat = "SOAP"; // SOAP, DAP

    // SOAP 형식 필드
    @Column(name = "subjective_text", columnDefinition = "TEXT")
    private String subjectiveText; // Subjective: 주관적 정보 (내담자 보고)

    @Column(name = "objective_text", columnDefinition = "TEXT")
    private String objectiveText; // Objective: 객관적 정보 (관찰된 행동)

    @Column(name = "assessment_text", columnDefinition = "TEXT")
    private String assessmentText; // Assessment: 평가 (임상적 인상)

    @Column(name = "plan_text", columnDefinition = "TEXT")
    private String planText; // Plan: 계획 (치료 계획)

    // DAP 형식 필드
    @Column(name = "data_text", columnDefinition = "TEXT")
    private String dataText; // Data: 데이터 (관찰 + 보고)

    // 진단 정보
    @Column(name = "diagnosis_summary", columnDefinition = "TEXT")
    private String diagnosisSummary;

    @Column(name = "diagnostic_impressions", columnDefinition = "TEXT")
    private String diagnosticImpressions;

    @Column(name = "treatment_recommendations", columnDefinition = "TEXT")
    private String treatmentRecommendations;

    // AI 생성 메타 정보
    @Column(name = "auto_generated")
    @Builder.Default
    private Boolean autoGenerated = true;

    @Column(name = "human_reviewed")
    @Builder.Default
    private Boolean humanReviewed = false;

    @Column(name = "reviewed_by_user_id")
    private Long reviewedByUserId;

    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;

    @Size(max = 50, message = "AI 모델명은 50자 이하여야 합니다.")
    @Column(name = "ai_model_used", length = 50)
    private String aiModelUsed;

    @Column(name = "generation_time_ms")
    private Integer generationTimeMs;

    @Column(name = "confidence_score", precision = 5, scale = 2)
    private BigDecimal confidenceScore; // 0-100

    // 비즈니스 메서드

    /**
     * SOAP 노트 여부 확인
     */
    public boolean isSOAPFormat() {
        return "SOAP".equalsIgnoreCase(this.reportFormat);
    }

    /**
     * DAP 노트 여부 확인
     */
    public boolean isDAPFormat() {
        return "DAP".equalsIgnoreCase(this.reportFormat);
    }

    /**
     * 진단 보고서 여부 확인
     */
    public boolean isDiagnosticReport() {
        return "DIAGNOSTIC".equalsIgnoreCase(this.reportType);
    }

    /**
     * 검토 완료 처리
     */
    public void markAsReviewed(Long reviewerUserId) {
        this.humanReviewed = true;
        this.reviewedByUserId = reviewerUserId;
        this.reviewedAt = LocalDateTime.now();
    }

    /**
     * 검토 취소 처리
     */
    public void unmarkReview() {
        this.humanReviewed = false;
        this.reviewedByUserId = null;
        this.reviewedAt = null;
    }

    /**
     * SOAP 섹션 완성도 확인 (모든 섹션이 채워졌는지)
     */
    public boolean isSOAPComplete() {
        return isSOAPFormat() && subjectiveText != null && !subjectiveText.trim().isEmpty()
                && objectiveText != null && !objectiveText.trim().isEmpty()
                && assessmentText != null && !assessmentText.trim().isEmpty() && planText != null
                && !planText.trim().isEmpty();
    }

    /**
     * DAP 섹션 완성도 확인
     */
    public boolean isDAPComplete() {
        return isDAPFormat() && dataText != null && !dataText.trim().isEmpty()
                && assessmentText != null && !assessmentText.trim().isEmpty() && planText != null
                && !planText.trim().isEmpty();
    }

    /**
     * 보고서 완성도 백분율
     */
    public int getCompletionPercentage() {
        if (isSOAPFormat()) {
            int filledSections = 0;
            if (subjectiveText != null && !subjectiveText.trim().isEmpty())
                filledSections++;
            if (objectiveText != null && !objectiveText.trim().isEmpty())
                filledSections++;
            if (assessmentText != null && !assessmentText.trim().isEmpty())
                filledSections++;
            if (planText != null && !planText.trim().isEmpty())
                filledSections++;
            return (filledSections * 100) / 4;
        } else if (isDAPFormat()) {
            int filledSections = 0;
            if (dataText != null && !dataText.trim().isEmpty())
                filledSections++;
            if (assessmentText != null && !assessmentText.trim().isEmpty())
                filledSections++;
            if (planText != null && !planText.trim().isEmpty())
                filledSections++;
            return (filledSections * 100) / 3;
        }
        return 0;
    }

    /**
     * 신뢰도 점수를 백분율 문자열로 반환
     */
    public String getConfidenceScorePercentage() {
        if (confidenceScore == null) {
            return "N/A";
        }
        return confidenceScore.intValue() + "%";
    }

    /**
     * 높은 신뢰도 여부 (80% 이상)
     */
    public boolean isHighConfidence() {
        return confidenceScore != null && confidenceScore.compareTo(new BigDecimal("80")) >= 0;
    }

    /**
     * 전체 텍스트 길이 (모든 섹션 합산)
     */
    public int getTotalTextLength() {
        int length = 0;
        if (subjectiveText != null)
            length += subjectiveText.length();
        if (objectiveText != null)
            length += objectiveText.length();
        if (assessmentText != null)
            length += assessmentText.length();
        if (planText != null)
            length += planText.length();
        if (dataText != null)
            length += dataText.length();
        if (diagnosisSummary != null)
            length += diagnosisSummary.length();
        return length;
    }

    @Override
    public String toString() {
        return "ClinicalReport{" + "id=" + getId() + ", consultationRecordId="
                + consultationRecordId + ", reportType='" + reportType + '\'' + ", reportFormat='"
                + reportFormat + '\'' + ", autoGenerated=" + autoGenerated + ", humanReviewed="
                + humanReviewed + ", aiModelUsed='" + aiModelUsed + '\'' + ", completionPercentage="
                + getCompletionPercentage() + "%" + '}';
    }
}
