/**
 * CSS 클래스 레지스트리
 * 자동 생성됨 - 수동 수정 금지
 * MindGarden 디자인 시스템 v2.0
 */

export const CSS_REGISTRY = {// 기존 클래스 (레거시)
  EXISTING: ['mg-button',
    'mg-card',
    'mg-dashboard-layout',
    'mg-sidebar',
    'mg-header',
    'mg-content',
    'mg-footer',
    'mg-modal',
    'mg-form',
    'mg-input',
    'mg-textarea',
    'mg-select',
    'mg-checkbox',
    'mg-radio',
    'mg-table',
    'mg-nav',
    'mg-tab',
    'mg-accordion',
    'mg-alert',
    'mg-badge',
    'mg-breadcrumb',
    'mg-button-group',
    'mg-card-body',
    'mg-card-header',
    'mg-card-footer',
    'mg-carousel',
    'mg-collapse',
    'mg-dropdown',
    'mg-list-group',
    'mg-pagination',
    'mg-popover',
    'mg-progress',
    'mg-scrollspy',
    'mg-spinner',
    'mg-toast',
    'mg-tooltip'],
  
  // 새 클래스 (v2.COLOR_CONSTANTS.ALPHA_TRANSPARENT)
  NEW: ['mg-v2-card',
    'mg-v2-card-header',
    'mg-v2-card-content',
    'mg-v2-card-footer',
    'mg-v2-card-stat',
    'mg-v2-card-user',
    'mg-v2-card-client',
    'mg-v2-card-consultant',
    'mg-v2-card-session',
    'mg-v2-card-message',
    'mg-v2-card-notification',
    'mg-v2-card-action',
    'mg-v2-card-info',
    'mg-v2-card-form',
    'mg-v2-button',
    'mg-v2-button-primary',
    'mg-v2-button-secondary',
    'mg-v2-button-success',
    'mg-v2-button-warning',
    'mg-v2-button-error',
    'mg-v2-button-info',
    'mg-v2-icon',
    'mg-v2-icon-wrapper',
    'mg-v2-icon-badge',
    'mg-v2-dashboard-layout',
    'mg-v2-dashboard-header',
    'mg-v2-dashboard-sidebar',
    'mg-v2-dashboard-main',
    'mg-v2-dashboard-content',
    'mg-v2-dashboard-footer',
    'mg-v2-section',
    'mg-v2-section-header',
    'mg-v2-section-content',
    'mg-v2-section-footer',
    'mg-v2-section-title',
    'mg-v2-section-subtitle',
    'mg-v2-tabs',
    'mg-v2-tabs-nav',
    'mg-v2-tab',
    'mg-v2-tab-content',
    'mg-v2-tab-panel',
    'mg-v2-form',
    'mg-v2-form-group',
    'mg-v2-form-label',
    'mg-v2-form-input',
    'mg-v2-form-textarea',
    'mg-v2-form-select',
    'mg-v2-form-checkbox',
    'mg-v2-form-radio',
    'mg-v2-form-error',
    'mg-v2-form-help',
    'mg-v2-table',
    'mg-v2-table-header',
    'mg-v2-table-body',
    'mg-v2-table-footer',
    'mg-v2-table-row',
    'mg-v2-table-cell',
    'mg-v2-table-header-cell',
    'mg-v2-modal',
    'mg-v2-modal-overlay',
    'mg-v2-modal-dialog',
    'mg-v2-modal-header',
    'mg-v2-modal-content',
    'mg-v2-modal-footer',
    'mg-v2-modal-close',
    'mg-v2-nav',
    'mg-v2-nav-brand',
    'mg-v2-nav-menu',
    'mg-v2-nav-item',
    'mg-v2-nav-link',
    'mg-v2-nav-dropdown',
    'mg-v2-nav-toggle',
    'mg-v2-button-group',
    'mg-v2-button-toolbar',
    'mg-v2-grid',
    'mg-v2-grid-item',
    'mg-v2-grid-row',
    'mg-v2-grid-col',
    'mg-v2-flex',
    'mg-v2-flex-item',
    'mg-v2-flex-center',
    'mg-v2-flex-between',
    'mg-v2-flex-around',
    'mg-v2-flex-evenly',
    'mg-v2-flex-start',
    'mg-v2-flex-end',
    'mg-v2-flex-column',
    'mg-v2-flex-row',
    'mg-v2-flex-wrap',
    'mg-v2-flex-nowrap',
    'mg-v2-m-xs',
    'mg-v2-m-sm',
    'mg-v2-m-md',
    'mg-v2-m-lg',
    'mg-v2-m-xl',
    'mg-v2-p-xs',
    'mg-v2-p-sm',
    'mg-v2-p-md',
    'mg-v2-p-lg',
    'mg-v2-p-xl',
    'mg-v2-gap-xs',
    'mg-v2-gap-sm',
    'mg-v2-gap-md',
    'mg-v2-gap-lg',
    'mg-v2-gap-xl',
    'mg-v2-h1',
    'mg-v2-h2',
    'mg-v2-h3',
    'mg-v2-h4',
    'mg-v2-h5',
    'mg-v2-h6',
    'mg-v2-text-sm',
    'mg-v2-text-md',
    'mg-v2-text-lg',
    'mg-v2-text-left',
    'mg-v2-text-center',
    'mg-v2-text-right',
    'mg-v2-text-justify',
    'mg-v2-font-normal',
    'mg-v2-font-medium',
    'mg-v2-font-semibold',
    'mg-v2-font-bold',
    'mg-v2-loading',
    'mg-v2-error',
    'mg-v2-success',
    'mg-v2-warning',
    'mg-v2-info',
    'mg-v2-disabled',
    'mg-v2-active',
    'mg-v2-hover',
    'mg-v2-focus',
    'mg-v2-mobile-only',
    'mg-v2-tablet-only',
    'mg-v2-desktop-only',
    'mg-v2-mobile-up',
    'mg-v2-tablet-up',
    'mg-v2-desktop-up'],
  
  // 예약어
  RESERVED: ['mg-v2-reserved',
    'mg-v2-internal',
    'mg-v2-system',
    'mg-v2-temp',
    'mg-v2-test',
    'mg-v2-debug',
    'mg-v2-deprecated',
    'mg-v2-legacy',
    'mg-v2-old',
    'mg-v2-new',
    'mg-v2-current',
    'mg-v2-future',
    'mg-v2-experimental',
    'mg-v2-beta',
    'mg-v2-alpha',
    'mg-v2-stable',
    'mg-v2-unstable',
    'mg-v2-broken',
    'mg-v2-fixed',
    'mg-v2-pending',
    'mg-v2-approved',
    'mg-v2-rejected',
    'mg-v2-draft',
    'mg-v2-final',
    'mg-v2-review',
    'mg-v2-ready',
    'mg-v2-not-ready',
    'mg-v2-complete',
    'mg-v2-incomplete',
    'mg-v2-valid',
    'mg-v2-invalid',
    'mg-v2-correct',
    'mg-v2-incorrect',
    'mg-v2-right',
    'mg-v2-wrong',
    'mg-v2-good',
    'mg-v2-bad',
    'mg-v2-nice',
    'mg-v2-ugly',
    'mg-v2-beautiful',
    'mg-v2-pretty',
    'mg-v2-cute',
    'mg-v2-cool',
    'mg-v2-hot',
    'mg-v2-warm',
    'mg-v2-cold',
    'mg-v2-fast',
    'mg-v2-slow',
    'mg-v2-quick',
    'mg-v2-easy',
    'mg-v2-hard',
    'mg-v2-simple',
    'mg-v2-complex',
    'mg-v2-basic',
    'mg-v2-advanced',
    'mg-v2-beginner',
    'mg-v2-expert',
    'mg-v2-pro',
    'mg-v2-amateur',
    'mg-v2-professional',
    'mg-v2-casual',
    'mg-v2-formal',
    'mg-v2-official',
    'mg-v2-unofficial',
    'mg-v2-public',
    'mg-v2-private',
    'mg-v2-secret',
    'mg-v2-hidden',
    'mg-v2-visible',
    'mg-v2-show',
    'mg-v2-hide',
    'mg-v2-display',
    'mg-v2-none',
    'mg-v2-block',
    'mg-v2-inline',
    'mg-v2-flex',
    'mg-v2-grid',
    'mg-v2-table',
    'mg-v2-list',
    'mg-v2-item',
    'mg-v2-container',
    'mg-v2-wrapper',
    'mg-v2-holder',
    'mg-v2-box',
    'mg-v2-panel',
    'mg-v2-window',
    'mg-v2-screen',
    'mg-v2-page',
    'mg-v2-section',
    'mg-v2-area',
    'mg-v2-zone',
    'mg-v2-region',
    'mg-v2-part',
    'mg-v2-piece',
    'mg-v2-element',
    'mg-v2-component',
    'mg-v2-module',
    'mg-v2-unit',
    'mg-v2-block',
    'mg-v2-chunk',
    'mg-v2-fragment',
    'mg-v2-segment',
    'mg-v2-division',
    'mg-v2-subdivision',
    'mg-v2-subsection',
    'mg-v2-subarea',
    'mg-v2-subzone',
    'mg-v2-subregion',
    'mg-v2-subpart',
    'mg-v2-subpiece',
    'mg-v2-subelement',
    'mg-v2-subcomponent',
    'mg-v2-submodule',
    'mg-v2-subunit',
    'mg-v2-subblock',
    'mg-v2-subchunk',
    'mg-v2-subfragment',
    'mg-v2-subsegment',
    'mg-v2-subdivision',
    'mg-v2-subsubdivision',
    'mg-v2-subsubsection',
    'mg-v2-subsubarea',
    'mg-v2-subsubzone',
    'mg-v2-subsubregion',
    'mg-v2-subsubpart',
    'mg-v2-subsubpiece',
    'mg-v2-subsubelement',
    'mg-v2-subsubcomponent',
    'mg-v2-subsubmodule',
    'mg-v2-subsubunit',
    'mg-v2-subsubblock',
    'mg-v2-subsubchunk',
    'mg-v2-subsubfragment',
    'mg-v2-subsubsegment',
    'mg-v2-subsubdivision']};

/**
 * CSS 클래스 검증 함수
 */
export const validateCSSClass = (className) => {const errors = [];
  const warnings = [];
  
  // DEFAULT_VALUES.CURRENT_PAGE. 네이밍 규칙 검증
  if (!className.startsWith('mg-') && !className.startsWith('mg-v2-')) {if (className.length > BUSINESS_CONSTANTS.MAX_RETRY_ATTEMPTS) {warnings.push(`클래스 '${className}'이 mg- 또는 mg-v2- 접두사를 사용하지 않습니다.`);}}
  
  // FORM_CONSTANTS.MIN_INPUT_LENGTH. 레거시 클래스와 충돌 검사
  if (className.startsWith('mg-') && !className.startsWith('mg-v2-')) {if (CSS_REGISTRY.EXISTING.includes(className)) {errors.push(`클래스 '${className}'이 레거시 클래스와 충돌합니다. mg-v2- 접두사를 사용하세요.`);}}
  
  // BUSINESS_CONSTANTS.MAX_RETRY_ATTEMPTS. 예약어 검사
  if (CSS_REGISTRY.RESERVED.some(reserved => className.includes(reserved))) {errors.push(`클래스 '${className}'이 예약어를 포함합니다.`);}
  
  return {errors, warnings};};

/**
 * CSS 클래스 등록 함수
 */
export const registerCSSClass = (className) => {if (!CSS_REGISTRY.NEW.includes(className)) {CSS_REGISTRY.NEW.push(className);
    return true;}
  return false;};

/**
 * CSS 클래스 존재 여부 확인
 */
export const hasCSSClass = (className) => {return CSS_REGISTRY.EXISTING.includes(className) || CSS_REGISTRY.NEW.includes(className);};

/**
 * CSS 클래스 목록 가져오기
 */
export const getCSSClasses = (type = 'all') => {switch (type) {case 'existing':
      return CSS_REGISTRY.EXISTING;
    case 'new':
      return CSS_REGISTRY.NEW;
    case 'reserved':
      return CSS_REGISTRY.RESERVED;
    case 'all':
    default:
      return [...CSS_REGISTRY.EXISTING, ...CSS_REGISTRY.NEW];}};

export default CSS_REGISTRY;
